name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.2
  google_nav_bar: ^5.0.6

flutter_native_splash:
  color: "#130021"
  image: assets/splash.png
  image_dark: assets/splash.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/Project-screenshot/
    - assets/images/tech-stack/
    - assets/images/social-media/
  uses-material-design: true
